# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465c285d4c1007483c96a5f984e4420fb056aebd1953d52193bc88504714d0a62f3d9d1636a87d7dbeb846b5ed0544ce872e0561b8fc3ebd39e53dfd7aae3ba5

test:
  secret_key_base: 03ae28ba18b5cfe004b5cf7bd39f9019565d08686269ad1924e7bcb5fa1a9844685d90cb919a78d3d8cd9998e1561459d1ce961790dd327352461e1a2035a6c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
